## Breast cancer Classification Using Logistic Regression

## importing Libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Importing dataset

In [2]:
dataset=pd.read_csv('breast_cancer.csv')

In [3]:
X=dataset.iloc[:,1:-1].values
Y=dataset.iloc[:,-1].values

In [4]:
print(X)

[[ 5  1  1 ...  3  1  1]
 [ 5  4  4 ...  3  2  1]
 [ 3  1  1 ...  3  1  1]
 ...
 [ 5 10 10 ...  8 10  2]
 [ 4  8  6 ... 10  6  1]
 [ 4  8  8 ... 10  4  1]]


# Splitting the dataset into training and test set

### We do this to identify the co-relations between features and labels 

In [5]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=0)

In [6]:
print(X_train)

[[10  1  1 ...  5  4  1]
 [ 1  1  1 ...  3  1  1]
 [ 5  1  1 ...  3  1  1]
 ...
 [ 1  1  1 ...  1  1  1]
 [ 3  1  1 ...  2  1  1]
 [10  9  7 ...  7  7  1]]


# Training The logistic regression model

In [7]:
from sklearn.linear_model import LogisticRegression

In [8]:
classifier=LogisticRegression(random_state=0)

In [9]:
classifier.fit(X_train,Y_train)

LogisticRegression(random_state=0)

# Predicting Test set result

In [10]:
Y_pred=classifier.predict(X_test)

In [11]:
print(Y_pred)

[2 2 4 4 2 2 2 4 2 2 4 2 4 2 2 2 4 4 4 2 2 2 4 2 4 4 2 2 2 4 2 4 4 2 2 2 4
 4 2 4 2 2 2 2 2 2 2 4 2 2 4 2 4 2 2 2 4 4 2 4 2 2 2 2 2 2 2 2 4 4 2 2 2 2
 2 2 4 2 2 2 4 2 4 2 2 4 2 4 4 2 4 2 4 4 2 4 4 4 4 2 2 2 4 4 2 2 4 2 2 2 4
 2 2 4 2 2 2 2 2 2 2 4 2 2 4 4 2 4 2 4 2 2 4 2 2 4 2]


# Making Confusion matrix
To check how many correct and how many incorrect predictions

In [12]:
from sklearn.metrics import confusion_matrix
cm= confusion_matrix(Y_test,Y_pred)
print(cm)

[[84  3]
 [ 3 47]]


here 84 correct predictons that tumor is benign that it is not breast cancer
47 correct predictions that the tumor is malignent that it is breast cancer
3 incorrect predictions that the tumor is benign false positive.
also 3 incorrect predictions that tumor us malignent false negative.

In [14]:
(84+47)/(84+47+3+3)

0.9562043795620438

# Computing accuracy with K fold cross validation

In [17]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = classifier, X = X_train, y = Y_train, cv = 10)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

Accuracy: 96.70 %
Standard Deviation: 1.97 %
